name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: node:23.7.0
    defaults:
      run:
        working-directory: ./vpos/checkout/javascript

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - run: yarn install --frozen-lockfile
    - run: yarn test
